project_id = "qjrvwcwmhuxygdanbxsz"

[functions.paystack-checkout]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.invite-staff]
verify_jwt = false

[functions.legal-assistant]
verify_jwt = false
