project_id = "qjrvwcwmhuxygdanbxsz"

[functions.hubtel-checkout]
verify_jwt = false

[functions.hubtel-webhook]
verify_jwt = false

[functions.invite-staff]
verify_jwt = false

[functions.legal-assistant]
verify_jwt = false
